name: grade-second-set
on: [push]
jobs:
  run-second-set:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
      - run: perl driver.pl -g 11
